<?php

namespace AppBundle\Repository;

/**
 * DomaineinterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineinterventionRepository extends \Doctrine\ORM\EntityRepository
{
}
