<?php

namespace AppBundle\Repository;

/**
 * PorteurprojetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PorteurprojetRepository extends \Doctrine\ORM\EntityRepository
{
}
