<?php

namespace AppBundle\Repository;

/**
 * SecteuractiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteuractiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
